### ISSUE TITLE
lava melting items

### ISSUE THREAD

**Issue by Necrofiend13** [FlenarnTemp/Nether-Additions#2]
Hey, great mod! love using it

I noticed the rod and fishes are not lava immune, similar to netherite and other lava fishing mods.

I can't do it with tags, it seems but, it is doable on the hard coding end. Perhaps an update to make the weeping rod and 4 fishes not be destroyed when touching lava? .IsImmuneToFire?

Thanks for the additions!

**Comment by FlenarnDev** [comment]
I'll do a little patch this weekend setting the fish to lava-immune, possibly the rod, I'll try and tweak the spawn position of the fished loot further to see if I can mitigate that issue, otherwise the rod might get set to lava-immune too.

**Comment by Loscan3D** [comment]
bro still hasn't solved it

**Comment by FlenarnDev** [comment]
Resolved in version 1.1.3, available for 1.20 -> 1.20.6.

Builds for 1.21 and later are in progress.
